"""The Python aggregate reduction, checked against the Rust guest's own vectors.

`cli/tests/vectors/aggregate_journal_vectors.json` is generated by
`protocol/bonsol-aggregate-reducer/examples/emit-aggregate-vectors.rs` and pinned on
the Rust side by `protocol/bonsol-aggregate-reducer/tests/cross_language_vectors.rs`.
This file pins the same vectors on the Python side, so the guest and the aggregator
cannot drift: a change to either reduction changes the file, and the other side then
fails.

Where the two disagree, `predict bind-aggregate` opens an aggregate job against a
journal hash the guest will never produce, and the job can never settle.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from kswarm_cli.aggregate import (
    AGGREGATE_COMMITTED_OUTPUTS_LEN,
    AGGREGATE_JOURNAL_LEN,
    AggregateError,
    aggregate_journal,
    build_aggregate_artifact,
    canonical_json_bytes,
    merkle_leaf_hash,
    merkle_node_hash,
    parse_branch_result_bytes,
    reduce_aggregate_artifact,
    sorted_branches_merkle_root,
    trim_count_from_bps,
    trimmed_mean_bps,
    weighted_mean_bps,
)
from kswarm_cli.encoding import sha256


VECTORS_PATH = Path(__file__).parent / "vectors" / "aggregate_journal_vectors.json"


def _vectors() -> dict:
    return json.loads(VECTORS_PATH.read_text(encoding="utf-8"))


def _accepted() -> list[dict]:
    return _vectors()["accepted"]


def _rejected() -> list[dict]:
    return _vectors()["rejected"]


def test_vectors_file_is_populated() -> None:
    assert len(_accepted()) >= 9
    assert len(_rejected()) >= 13


@pytest.mark.parametrize("vector", _accepted(), ids=lambda vector: vector["name"])
def test_accepted_vector_reduces_to_its_recorded_journal(vector: dict) -> None:
    journal = aggregate_journal(vector["artifact"].encode("utf-8"))
    assert journal.input_digest.hex() == vector["input_digest"]
    assert journal.reduction.combiner_id == vector["combiner_id"]
    assert journal.reduction.params_digest.hex() == vector["combiner_params_digest"]
    assert journal.reduction.result_value == vector["result_value"]
    assert journal.reduction.branch_count == vector["branch_count"]
    assert journal.reduction.merkle_root.hex() == vector["merkle_root"]
    assert journal.committed_outputs.hex() == vector["committed_outputs"]
    assert journal.output_digest.hex() == vector["output_digest"]
    assert journal.journal_hash.hex() == vector["journal_hash"]
    assert len(journal.committed_outputs) == AGGREGATE_COMMITTED_OUTPUTS_LEN
    assert len(journal.journal_bytes) == AGGREGATE_JOURNAL_LEN == 105


@pytest.mark.parametrize("vector", _rejected(), ids=lambda vector: vector["name"])
def test_rejected_vector_is_still_rejected(vector: dict) -> None:
    with pytest.raises(AggregateError):
        reduce_aggregate_artifact(vector["artifact"].encode("utf-8"))


def test_journal_field_offsets_match_the_documented_layout() -> None:
    vector = _accepted()[0]
    journal = aggregate_journal(vector["artifact"].encode("utf-8"))
    raw = journal.journal_bytes
    assert raw[:32] == journal.input_digest
    assert raw[32] == journal.reduction.combiner_id
    assert raw[33:65] == journal.reduction.params_digest
    assert int.from_bytes(raw[65:69], "little") == journal.reduction.result_value
    assert int.from_bytes(raw[69:73], "little") == journal.reduction.branch_count
    assert raw[73:] == journal.reduction.merkle_root
    assert journal.output_digest == sha256(journal.committed_outputs)


def test_builder_produces_the_bytes_the_vectors_carry() -> None:
    """The builder and the generator must agree, or a bound job would be unprovable."""

    vector = next(item for item in _accepted() if item["name"] == "weighted-mean-uniform")
    artifact = json.loads(vector["artifact"])
    rebuilt = build_aggregate_artifact(
        parent_run=artifact["parent_run"],
        parent_manifest_cid=artifact["parent_manifest_cid"],
        output_schema_hash=artifact["output_schema_hash"],
        combiner=artifact["combiner"],
        combiner_parameters=artifact["combiner_parameters"],
        branches=[
            {
                "branch_index": branch["branch_index"],
                "job": branch["job"],
                "output_cid": branch["output_cid"],
                "result_bytes": branch["result_bytes"],
                "weight": branch["weight"],
            }
            for branch in artifact["branches"]
        ],
    )
    assert rebuilt == vector["artifact"].encode("utf-8")


def test_builder_derives_the_result_hash_rather_than_trusting_it() -> None:
    receipt = bytes.fromhex(json.loads(_accepted()[0]["artifact"])["branches"][0]["result_bytes"])
    artifact = build_aggregate_artifact(
        parent_run="Run",
        parent_manifest_cid="cid",
        output_schema_hash="00" * 32,
        combiner="weighted-mean",
        combiner_parameters={},
        branches=[
            {
                "branch_index": 0,
                "job": "J",
                "output_cid": "c",
                "result_bytes": receipt.hex(),
                "result_hash": "ff" * 32,
                "weight": 1,
            }
        ],
    )
    assert json.loads(artifact)["branches"][0]["result_hash"] == sha256(receipt).hex()


def test_builder_sorts_branches_by_index() -> None:
    artifact_bytes = _accepted()[2]["artifact"].encode("utf-8")
    branches = json.loads(artifact_bytes)["branches"]
    shuffled = list(reversed(branches))
    rebuilt = build_aggregate_artifact(
        parent_run=json.loads(artifact_bytes)["parent_run"],
        parent_manifest_cid=json.loads(artifact_bytes)["parent_manifest_cid"],
        output_schema_hash=json.loads(artifact_bytes)["output_schema_hash"],
        combiner="weighted-mean",
        combiner_parameters={},
        branches=shuffled,
    )
    assert rebuilt == artifact_bytes


def test_canonical_json_is_sorted_compact_and_utf8() -> None:
    assert canonical_json_bytes({"b": 1, "a": {"d": 2, "c": 3}}) == b'{"a":{"c":3,"d":2},"b":1}'
    assert canonical_json_bytes({"a": None}) == b'{"a":null}'
    assert canonical_json_bytes({"a": "é"}).decode("utf-8") == '{"a":"é"}'


def test_merkle_root_domain_separates_leaves_from_nodes() -> None:
    a = bytes([0x11]) * 32
    b = bytes([0x22]) * 32
    assert sorted_branches_merkle_root([a]) == merkle_leaf_hash(a)
    assert sorted_branches_merkle_root([a]) != a
    assert sorted_branches_merkle_root([b, a]) == merkle_node_hash(merkle_leaf_hash(a), merkle_leaf_hash(b))
    # The odd node is promoted, never paired with itself, so this pair cannot collide.
    assert sorted_branches_merkle_root([a, b, b]) != sorted_branches_merkle_root([a, b, b, b])
    with pytest.raises(AggregateError):
        sorted_branches_merkle_root([])


def test_exact_integer_rounding_is_half_up() -> None:
    assert weighted_mean_bps([(1, 1), (2, 1)]) == 2
    assert weighted_mean_bps([(1, 1), (1, 1), (2, 1)]) == 1
    assert weighted_mean_bps([(0, 3), (10000, 1)]) == 2500
    assert trimmed_mean_bps([1, 2, 2, 4], 0) == 2
    assert trim_count_from_bps(10, 1000) == 1
    assert trim_count_from_bps(9, 1000) == 0
    with pytest.raises(AggregateError):
        weighted_mean_bps([(10001, 1)])
    with pytest.raises(AggregateError):
        trim_count_from_bps(2, 10000)


def test_strict_mfb2_parser_rejects_a_second_spelling() -> None:
    receipt = bytes.fromhex(json.loads(_accepted()[0]["artifact"])["branches"][0]["result_bytes"])
    parsed = parse_branch_result_bytes(receipt)
    assert parsed.branch_index == 0
    assert parsed.output_kind == "scalar"
    assert parsed.result_hash == sha256(receipt)
    with pytest.raises(AggregateError):
        parse_branch_result_bytes(receipt + b"\x00")
    with pytest.raises(AggregateError):
        parse_branch_result_bytes(receipt[:-1])
    with pytest.raises(AggregateError):
        parse_branch_result_bytes(b"XFB2" + receipt[4:])
    unknown_flag = bytearray(receipt)
    unknown_flag[10] |= 0x20
    with pytest.raises(AggregateError):
        parse_branch_result_bytes(bytes(unknown_flag))
